#!/bin/sh
# Part of spindle http://asbradbury.org/projects/spindle
#
# See LICENSE file for copyright and license details

set -e

. ./common

CURIMG=stage1.$IMGFORMAT

# Security for these keys doesn't matter: just using ssh as it's convenient 
# It's not easy to disable authentication, so just use passwordless keys.

# could be generated with dropbearkey -t rsa -f
# ./etc/dropbear/dropbear_rsa_host_key and base64 encoding the result
DROPBEAR_RSA_KEY=$(cat <<EOF
AAAAB3NzaC1yc2EAAAADAQABAAABAQCALZwM1jtqQ8g6wU+aej1fnG2aXWyh5gWIaf0o7Ju0Sucv
5xsFIUTn+4nLWUhcHwvsYo77VGkjmmPWEDW6oldnG9ZAKWa/Ubk42QDi1eS7VIh8pho73Y0pk7Gr
tms04zPe1D7KWBJKToKRgrOPqI0aLE0WjU2OX2X9QHPDSsQ5lJvnE757bYg2kMopPpOH/NuQIYDP
X/Gk/iIPK0z+xBs0LewYueAljnSzphUndyS41koo2RE1ZVHj+FCl0QklsuqB8ei8KBW6VSJXz9nU
68njFsCBC9unnfr8AU0+DWVzQNNsP3dUn7PEG9uUWRcxG6fNAKkiKeyAC1ZE5Kfz6WaPAAABACCG
MjoppCLnNyf9hErw6KDZqxAH07hTCyVdq5DWVP4PIZGMpVUMZ5UrxP+11IAXmqltKtXISfNwShP3
wgJtDhuKOzfFqZ4zSPoNSkXEu4jzPrzOUwrMwXSC1wr4u0RMwI0yswoaBe4X9NaiYRi7Tq6M/jSS
P1M4jsMPtzAfSSJI4JHh6ryx04CJnWz2lBDGXnldZFV25kyktkztkL+maurXdJFUSuUtDT3/tecw
RQJIHc4+LEAA1IYOq6g01bNJUitERHHWtPnof13l6xEb2QY8LXAOiAC2eIeaN+TyEBnpuSxAeq1s
IsyW48XhVl2cz05V8zOkfNm5KYSireMFrQkAAACBAKlxnjromVbC0FTW9s1dGdltsR6vgwrYTnxE
pkLEWo3pbFTMFk7sX9NIJieGVY6jJVt+LJQCEVCGFEJMBnByJjmVFKTfTANzavanf7DHi4ygRJei
voGuRLy/yMn0SZ3wkPWVuqMuTfUdQOmmlrclJA2OgiPVVR/GtFI4zMreJwYXAAAAgQDBp6Ed1qHZ
xp4fLmVoYTzIw5LRPjGexNHHGDWQYu14+5+l3Z/4IJM71vPvCCez1V8oAUpRzRnSclLmTeY/Axtt
kt67Y+9TKY7iwILinXXhtazHkJ16YBVEBbqMfc5S4C/oVlfkzNe32gnaimUW5r+rISQYBaUbsZLB
6pOkMTDmSQ==
EOF
)

# could be generated with sh-keygen -t dsa -f qemu_arm_key -N ""
PRIVATE_SSH_KEY=$(cat <<EOF
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAwHmdFI02rXXHw4PfiQRgQGV7nwBwJGfwplweHFYWgoXeBWef
u804r8UpdtKCOaMkzjbWaoxulj9BO0aFWNSD1Xdr3Oq1UlYHs8hnDClQ+ZReLdym
rEBPFG1VbA5Eh95zjEAs68U1qA4GRu8AIkdLU8OJp7EvKPnRsVMxfLUny+/3xK0y
76oz+evmaRkIjYWa5rXy53582ZFphBUwUSZ+dJhalcvfy9I8+ihxIxnXa6O5c0hD
n+/AOdJ88qyCc1YH869p7qnJ27lyW7C3Z3QijgQ5XvrLFLk5lnbrZsa9zO4ua+lU
9fZctTJlBaOORrZwrizm0IdE2QyqxZtVNuND2wIDAQABAoIBAAMaswbe1C/uA1/K
47MRCABh4qGI30YnCwGT4MRyOwC16gPKTRA5Wh2zn1yUPpdxYymURtcHFs2DjajI
FWR+YPXzbCDvBCekzZD/vXG7xNuRogc5VNLYYq4gqU0J2d8bHl/3tQHEd34TY9SH
DEiBP9zE/ZZfzDPr+47Rma26Oj8Ww4bkQe+AI9bTKS4wV0U8STyQPIUfFKiOKKxG
GGZCk85D45zNse9ITWnjKfI0RoIII+0kUOKF/uxJDGheXefZ//nWaMtMUYoPCL3l
8K8r1l+KJVPnf6Xqq4L4OJZXu1tJdfioeAQSNg6p5BNJQRJnmP++BefOxbQix7pT
JSSkrVECgYEA8rayuTFa8mie/xpBFS4pTKP0WQMjvVhcfNijdx01TOabLfIsWEmq
sJqDj9x+QygbC2s/4FKJJwUCX3/dQjZTE80vPJnrBXLK1iEn/t/2JLLDQhT0hj5Q
4iztgM4DYLa+cui9Vk9P8WSVHSc9Xe1K90jquKGK3hMlxO4bTHjLwikCgYEAywLj
wEfbpZpC+OdM0c9crP7Tvtx1cV0p+G61nf2yNPvG88w8xvgLxQBSVPSxNEe8hQg3
XgNRa10GMuceI9lAB1K6op/MXpi/bjpecBYEwydrYdfAJApnBtlA3YC1Y58SH0SU
N62eZUpUcXu+/Ngq890jv8idlFP0AmU3BSkvfmMCgYB61hv9vgzZQjm1wgPORF6C
ezffFMexvFaSmNGiJxYipVNEHZxz0lSgrJKI7H66XkHRtaXOUfc32EErM/s212eU
TfPqJ7vaNg6R8JXdWFuqlw5bE1/t0Pv+e953ocvz1ojsfv3UAK/k65LL/mAAeWfH
Xw/sAVXWrroewKLwQPJegQKBgQCx2Vg5LTqpu5kMgWX1MNqZ260ZOf3RULLiJ+sH
/CdQ73n+P2DHVqrI7V0zfCJ6EJaBXQ9UV0fO7PHvSjZHZZ4ITFug+KmL/flG0e/F
9iQ566DRWLfFWy+i+lUvOACww7yWk/fdR0bKqfGMccKBs8b9WTBmZZRXS60rJAyt
gsVOzQKBgQCQiV7NVw6Pyn20c6KfrTJa41TA4l1qdyMvL9P0Iml7tytlTaY04Z80
TwuHX0aDVqc8Dtg2iTavfRU5/wsCMocbfWqAU+iD7c3163soKh5Yo1IizsNkx08c
GNI7/uQGCoYHugNdm6AFe+gcHiGhWzEtCPYiI+jWgSQIqUq/u/XbkQ==
-----END RSA PRIVATE KEY-----
EOF
)

# could be generated with sh-keygen -t rsa -f qemu_arm_key -N ""
PUBLIC_SSH_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAeZ0UjTat\
dcfDg9+JBGBAZXufAHAkZ/CmXB4cVhaChd4FZ5+7zTivxSl20oI5oyTONtZqjG6W\
P0E7RoVY1IPVd2vc6rVSVgezyGcMKVD5lF4t3KasQE8UbVVsDkSH3nOMQCzrxTWo\
DgZG7wAiR0tTw4mnsS8o+dGxUzF8tSfL7/fErTLvqjP56+ZpGQiNhZrmtfLnfnzZ\
kWmEFTBRJn50mFqVy9/L0jz6KHEjGddro7lzSEOf78A50nzyrIJzVgfzr2nuqcnb\
uXJbsLdndCKOBDle+ssUuTmWdutmxr3M7i5r6VT19ly1MmUFo45GtnCuLObQh0TZ\
DKrFm1U240Pb root@8525a488452f"

setup_dropbear() {
  chmod +x dropbearmulti-armv6l &&
  cp -a dropbearmulti-armv6l qemu_rootfs/bin/dropbear &&
  cd qemu_rootfs/bin &&
  ln -s dropbear scp &&
  cd "$OLDPWD" &&
  mkdir -p qemu_rootfs/etc/dropbear &&
  printf "%s" "$DROPBEAR_RSA_KEY" | base64 -d > qemu_rootfs/etc/dropbear/dropbear_rsa_host_key &&
  printf "%s" "$PRIVATE_SSH_KEY" > qemu_arm_key &&
  chmod 600 qemu_arm_key &&
  printf "%s" "$PUBLIC_SSH_KEY" > qemu_arm_key.pub &&
  cp -a qemu_arm_key.pub qemu_rootfs/root
}

INIT_SH=$(cat <<\EOF
#!/bin/sh

export HOME=/home/root

mount -t proc proc proc
mount -t sysfs sys sys
mount -t devtmpfs dev dev
mkdir -p dev/pts
mount -t devpts dev/pts dev/pts

export PS1='($HOST) \w \$ '

export PATH

ifconfig eth0 10.0.2.15
route add default gw 10.0.2.2

[ "$(date +%s)" -lt 1000 ] && rdate 10.0.2.2 # or time-b.nist.gov

mount -t tmpfs /tmp /tmp

mount -o noatime /dev/sdb2 /mnt
[ -d /mnt/tmp ] && mount --bind /tmp /mnt/tmp

mount -t tmpfs /home /home
mkdir -p /home/root
cd $HOME

mkdir -p /home/root/.ssh
cp -a /root/qemu_arm_key.pub /home/root/.ssh/authorized_keys
chmod 600 /home/root/.ssh/authorized_keys
dropbear -E -s
exec /sbin/oneit -c /dev/ttyAMA0 /bin/ash
EOF
)

replace_init_sh() {
  printf "%s" "$INIT_SH" > qemu_rootfs/sbin/init.sh
}

do_second_stage_debootstrap() {
  onvm_chroot sh -ex - <<EOF
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
./debootstrap/debootstrap --second-stage
apt-get clean
EOF
}

# Made redundant by firmware debs
configure_udev() {
  onvm_chroot sh -e - <<EOF
  printf 'SUBSYSTEM=="vchiq", GROUP="video", MODE="0660"\n' > /etc/udev/rules.d/10-local-rpi.rules
EOF
}

cd $WORKDIR
dotask branch_image ../$OUTDIR/stage0.$IMGFORMAT $CURIMG
dotask download_if_necessary http://asbradbury.org/tmp/raspi/simple-root-filesystem-armv6l.tar.bz2
dotask download_if_necessary http://asbradbury.org/tmp/raspi/system-image-armv6l.tar.bz2
dotask download_if_necessary http://asbradbury.org/tmp/raspi/dropbearmulti-armv6l
[ -f zImage ] || tar -xf system-image-armv6l.tar.bz2 --strip-components=1 system-image-armv6l/zImage
tar -xvf simple-root-filesystem-armv6l.tar.bz2
rm -rf qemu_rootfs
mv simple-root-filesystem-armv6l qemu_rootfs 
dotask setup_dropbear
dotask replace_init_sh
dotask mksquashfs qemu_rootfs qemu_rootfs.sqf -noappend -all-root
dotask run_qemu $CURIMG
dotask do_second_stage_debootstrap
#dotask configure_udev
dotask shutdown_qemu
dotask finish_image
